name: ci-authserver

on:
  push:
    branches:
      - master
      - '*release*'
      - develop
    paths:
      - 'ProjectTemplates/AuthorizationServer/**'
  pull_request:
    branches:
      - master
      - '*release*'
      - develop
    paths:
      - 'ProjectTemplates/AuthorizationServer/**' 
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Install Docker Compose plugin (v2+)
      run: |
        mkdir -p ~/.docker/cli-plugins/
        curl -SL https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
        chmod +x ~/.docker/cli-plugins/docker-compose
    - name: Build and run containers
      run: |
        cd "$GITHUB_WORKSPACE/ProjectTemplates/AuthorizationServer"
        docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d --build
    - name: Wait for app to become healthy (simple curl check)
      run: |
        echo "Waiting for auth server to respond..."
        for i in {1..30}; do
          if curl -s http://localhost:8080/swagger/index.html >/dev/null; then
            echo "Auth server is up!"
            exit 0
          fi
          sleep 3
        done
        echo "Auth server did not start in time."
        exit 1
    - name: Run integration tests
      run: |
        cd "$GITHUB_WORKSPACE/ProjectTemplates/AuthorizationServer"
        docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm testrunner