name: ci-meshes

on:
  workflow_dispatch:
  push:
    branches:
      - master 
      - '*release*'
      - develop
    paths:
      - 'Source/Meshes/**'
  pull_request:
    branches:
      - master 
      - '*release*'
      - develop
    paths:
      - 'Source/Meshes/**' 

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5
    - name: Detect changed folders
      id: filter
      uses: dorny/paths-filter@v3
      with:
        filters: |
          meshes:
            - 'Source/Meshes/DHI.Services.Meshes/**'
          webapi:
            - 'Source/Meshes/DHI.Services.Meshes.WebApi/**'
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: | 
        dotnet restore ./Source/Meshes/DHI.Services.Meshes.sln -s https://api.nuget.org/v3/index.json 
        dotnet restore ./Source/Meshes/DHI.Services.Meshes.WebApi.sln -s https://api.nuget.org/v3/index.json
    - name: Build domain
      run: dotnet build ./Source/Meshes/DHI.Services.Meshes.sln --no-restore
    - name: Build Web API
      run: dotnet build ./Source/Meshes/DHI.Services.Meshes.WebApi.sln --no-restore
    - name: Test domain
      run: dotnet test ./Source/Meshes/DHI.Services.Meshes.Test/DHI.Services.Meshes.Test.csproj --no-build --verbosity normal
    - name: Test Web API
      run: dotnet test ./Source/Meshes/DHI.Services.Meshes.WebApi.Host.Test/DHI.Services.Meshes.WebApi.Host.Test.csproj --no-build --verbosity normal
    - name: Pack & Push Meshes
      if: |
        github.ref == 'refs/heads/master' &&
        steps.filter.outputs.meshes == 'true'
      shell: cmd
      working-directory: Source\Meshes\DHI.Services.Meshes\nuget
      env:
        NUGET_API_KEY_PUBLISH: ${{ secrets.NUGET_API_KEY_PUBLISH }}
      run: PackAndPushPublish.bat yes
    - name: Pack & Push Meshes.WebApi
      if: |
        github.ref == 'refs/heads/master' &&
        steps.filter.outputs.webapi == 'true'
      shell: cmd
      working-directory: Source\Meshes\DHI.Services.Meshes.WebApi\nuget
      env:
        NUGET_API_KEY_PUBLISH: ${{ secrets.NUGET_API_KEY_PUBLISH }}
      run: PackAndPushPublish.bat yes